using System.Globalization;
using AwesomeAssertions;

namespace Contour.Core.Tests;

/// <summary>
/// Tests that verify LCC projection match the Python AEDT MakeContours script.
/// Python: aedt.createINMSpatialRef(lat, lon) -> projectAs(projected_spatial_ref)
/// C#:     LambertConformalConic(lat, lon)     -> Forward(lon, lat)
/// </summary>
[TestClass]
public class LambertConformalConicTests
{
    [TestMethod]
    [DataRow(-111.702216634548, 36.8133770762867)]
    [DataRow(-71.28901, 42.469889447)]
    [DataRow(-122.542363498088, 37.4853922964778)]
    [DataRow(72.84, 19.06)]
    [DataRow(-103.461871974262, 43.8322573614683)]
    [DataRow(-104.673828, 39.849312)]
    public void Lcc_AirportProjectsToOrigin_AllTestcases(double lon, double lat)
    {
        var lcc = new LambertConformalConic(lat, lon);
        var (easting, northing) = lcc.Forward(lon, lat);

        easting.Should().BeApproximately(0.0, 1e-6, $"Airport ({lat}, {lon}) easting should be 0");
        northing.Should().BeApproximately(0.0, 1e-6, $"Airport ({lat}, {lon}) northing should be 0");
    }

    [TestMethod]
    [DataRow(-111.702216634548, 36.8133770762867)]
    [DataRow(-71.28901, 42.469889447)]
    [DataRow(-122.542363498088, 37.4853922964778)]
    [DataRow(72.84, 19.06)]
    [DataRow(-103.461871974262, 43.8322573614683)]
    [DataRow(-104.673828, 39.849312)]
    public void Lcc_RoundTrip_RecoversOriginalCoordinates(double lon, double lat)
    {
        var lcc = new LambertConformalConic(lat, lon);

        // Project a point offset from the airport
        double testLon = lon + 0.5;
        double testLat = lat + 0.3;

        var (easting, northing) = lcc.Forward(testLon, testLat);
        var (recoveredLon, recoveredLat) = lcc.Inverse(easting, northing);

        recoveredLon.Should().BeApproximately(testLon, 1e-9, "Round-trip longitude");
        recoveredLat.Should().BeApproximately(testLat, 1e-9, "Round-trip latitude");
    }

    [TestMethod]
    public void Lcc_KnownOffset_ProducesReasonableDistance()
    {
        // A point 1° east of the airport at the same latitude should be ~88km east
        // (at ~37°N, 1° lon ≈ cos(37°) * 111km ≈ 88.7km)
        double lat = 36.8133770762867;
        double lon = -111.702216634548;

        var lcc = new LambertConformalConic(lat, lon);
        var (easting, _) = lcc.Forward(lon + 1.0, lat);

        // At 36.8°N: 1° longitude ≈ cos(36.8°) * 111,320m ≈ 89,100m
        easting.Should().BeApproximately(89100, 500, "1° longitude offset should be ~89km easting");
    }

    [TestMethod]
    public void Lcc_MatchesPythonWktParameters()
    {
        // Verify our projection uses the same parameters as Python's createINMSpatialRef:
        // PROJCS['Custom_Lambert_Conformal_Conic',
        //   GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]]],
        //   PROJECTION['Lambert_Conformal_Conic'],
        //   PARAMETER['False_Easting',0.0],
        //   PARAMETER['False_Northing',0.0],
        //   PARAMETER['Central_Meridian', lon],
        //   PARAMETER['Standard_Parallel_1', lat],
        //   PARAMETER['Standard_Parallel_2', lat],
        //   PARAMETER['Latitude_Of_Origin', lat],
        //   UNIT['Meter',1.0]]
        //
        // With both standard parallels = lat of origin, this is a tangential (1SP) LCC.
        // n = sin(lat), which our code computes directly.
        //
        // Validate: airport at false easting/northing of 0 → projects to (0,0)
        // and a symmetric test: points equidistant north/south of origin should have equal |northing|

        double lat = 36.8133770762867;
        double lon = -111.702216634548;
        var lcc = new LambertConformalConic(lat, lon);

        // Airport → origin
        var (e0, n0) = lcc.Forward(lon, lat);
        Math.Abs(e0).Should().BeLessThan(1e-6);
        Math.Abs(n0).Should().BeLessThan(1e-6);

        // Points offset equally east/west should have symmetric easting
        var (eEast, _) = lcc.Forward(lon + 0.1, lat);
        var (eWest, _) = lcc.Forward(lon - 0.1, lat);
        eEast.Should().BeApproximately(-eWest, 1.0, "East/west easting should be symmetric");
    }

    // ──────────────────────────────────────────
    // Comparison against Esri reference projection output
    // Generated by: export_projected_points.py (requires arcpy)
    // Files at: %TEMP%/projection_reference/tc{id}_projected.csv
    // ──────────────────────────────────────────

    private static readonly string ReferenceDir = Path.Combine("projection_reference");

    [TestMethod]
    [DataRow(1, -71.28901, 42.469889447)]
    [DataRow(2, -122.542363498088, 37.4853922964778)]
    [DataRow(3, -111.702216634548, 36.8133770762867)]
    [DataRow(4, 72.84, 19.06)]
    [DataRow(5, -103.461871974262, 43.8322573614683)]
    [DataRow(6, -104.673828, 39.849312)]
    public void ProjectedPoints_MatchEsriReference(int id, double airportLon, double airportLat)
    {
        // Compare our LCC.Forward() output against Esri's projectAs() output
        // for every point in the test case.

        // Reference files generated by: export_projected_points.py
        // CSV format: longitude,latitude,easting,northing,value
        string refFile = Path.Combine(ReferenceDir, $"{id}_projected.csv");

        if (!File.Exists(refFile))
        {
            Assert.Inconclusive($"Esri reference file not found: {refFile}.");
        }

        var lcc = new LambertConformalConic(airportLat, airportLon);

        int count = 0;
        double maxEastingDiff = 0;
        double maxNorthingDiff = 0;
        double sumEastingSq = 0;
        double sumNorthingSq = 0;

        foreach (string line in File.ReadLines(refFile).Skip(1)) // skip header
        {
            string[] parts = line.Split(',');
            if (parts.Length < 4) continue;

            double lon = double.Parse(parts[0], CultureInfo.InvariantCulture);
            double lat = double.Parse(parts[1], CultureInfo.InvariantCulture);
            double esriEasting = double.Parse(parts[2], CultureInfo.InvariantCulture);
            double esriNorthing = double.Parse(parts[3], CultureInfo.InvariantCulture);

            var (ourEasting, ourNorthing) = lcc.Forward(lon, lat);

            double eDiff = Math.Abs(ourEasting - esriEasting);
            double nDiff = Math.Abs(ourNorthing - esriNorthing);

            maxEastingDiff = Math.Max(maxEastingDiff, eDiff);
            maxNorthingDiff = Math.Max(maxNorthingDiff, nDiff);
            sumEastingSq += eDiff * eDiff;
            sumNorthingSq += nDiff * nDiff;
            count++;
        }

        count.Should().BeGreaterThan(0, "Reference file should contain data");

        double rmseEasting = Math.Sqrt(sumEastingSq / count);
        double rmseNorthing = Math.Sqrt(sumNorthingSq / count);

        Console.WriteLine($"{id}: {count} points compared");
        Console.WriteLine($"  Easting  — RMSE: {rmseEasting:E4}m, Max: {maxEastingDiff:E4}m");
        Console.WriteLine($"  Northing — RMSE: {rmseNorthing:E4}m, Max: {maxNorthingDiff:E4}m");

        // The Snyder LCC formulas and Esri's engine should agree to sub-millimeter precision
        // for points within a few hundred km of the origin. Allow 0.01m (1cm) tolerance
        // to account for any floating-point differences between implementations.
        maxEastingDiff.Should().BeLessThan(0.01, $"{id}: max easting difference should be < 1cm");
        maxNorthingDiff.Should().BeLessThan(0.01, $"{id}: max northing difference should be < 1cm");
    }
}
